# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pytorch_educative',
                'doc_host': 'https://nesaboz.github.io',
                'git_url': 'https://github.com/nesaboz/pytorch_educative',
                'lib_path': 'pytorch_educative'},
  'syms': {'pytorch_educative.core': {'pytorch_educative.core.foo': ('core.html#foo', 'pytorch_educative/core.py')}}}
